pipeline{
    agent any
    stages{
        stage('Run-stress-test'){
            steps{
              sh "cd run-stress-test/sample-gradle-gatling && ./gradlew gatlingRun"
            }
        }
    }
}
